# Generated by Django 5.2.17 on 2026-08-31 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(blank=True, max_length=100)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('source_file', models.FileField(blank=True, null=True, upload_to='invoices/%Y/%m/')),
                ('status', models.CharField(choices=[('IMPORTED', 'Importée'), ('NEEDS_REVIEW', 'À vérifier'), ('COMPLETE', 'Complète'), ('ERROR', 'Erreur')], default='IMPORTED', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-invoice_date', '-imported_at'],
            },
        ),
        migrations.CreateModel(
            name='ScrapeJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('RUNNING', 'En cours'), ('SUCCESS', 'Terminé'), ('FAILED', 'Échoué')], default='PENDING', max_length=20)),
                ('log', models.TextField(blank=True)),
                ('invoices_found', models.IntegerField(default=0)),
                ('invoices_created', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('parser_key', models.CharField(blank=True, max_length=32)),
                ('is_scrapable', models.BooleanField(default=False, help_text="Whether 'Gather new invoices' knows how to fetch this supplier automatically.")),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(default=1)),
                ('total_volume', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('unit_cost_ht', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('total_ht', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('taxes', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('vat_rate', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('category', models.CharField(blank=True, max_length=255)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='invoices.invoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_lines', to='inventory.product')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='invoices.supplier'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(condition=models.Q(('invoice_number', ''), _negated=True), fields=('supplier', 'invoice_number'), name='unique_supplier_invoice_number'),
        ),
    ]
