# Generated by Django 5.2.17 on 2026-08-31 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_scrapejob_progress_scrapejob_range_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceline',
            name='colisage',
            field=models.IntegerField(default=1),
        ),
    ]
