# Generated by Django 5.2.17 on 2026-09-02 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_invoiceline_colisage'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='reconciliation_adjustment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
