# Generated by Django 5.2.17 on 2026-09-02 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_invoice_reconciliation_adjustment'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapejob',
            name='kind',
            field=models.CharField(choices=[('GATHER', 'Récupération'), ('TEST', 'Test de motif')], default='GATHER', max_length=10),
        ),
        migrations.AddField(
            model_name='scrapejob',
            name='test_matches',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='InvoiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('parser_key', models.CharField(blank=True, max_length=32)),
                ('source_kind', models.CharField(choices=[('EMAIL', 'Email'), ('WEBSITE', 'Site web')], default='EMAIL', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text="Whether 'Récupérer les nouvelles factures' should gather this type automatically.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_types', to='invoices.supplier')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmailInvoiceSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_pattern', models.CharField(help_text="Expression régulière testée sur l'expéditeur.", max_length=500)),
                ('subject_pattern', models.CharField(blank=True, help_text="Expression régulière testée sur l'objet (vide = tous).", max_length=500)),
                ('body_pattern', models.CharField(blank=True, help_text='Expression régulière testée sur le contenu (vide = tous).', max_length=500)),
                ('attachment_pattern', models.CharField(blank=True, default='(?i)\\.pdf$', help_text='Expression régulière testée sur le nom de la pièce jointe.', max_length=200)),
                ('invoice_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_source', to='invoices.invoicetype')),
            ],
        ),
    ]
