# Generated by Django 5.2.17 on 2026-09-03 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0008_scrapejob_cancel_requested_alter_scrapejob_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicetype',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Inclure ce type dans « Récupérer les nouvelles factures ».'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='is_scrapable',
            field=models.BooleanField(default=False, help_text='Si « Récupérer les nouvelles factures » sait aller les chercher tout seul.'),
        ),
    ]
