# Generated by Django 5.2.17 on 2026-09-03 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0009_help_text_fr'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapejob',
            name='last_heartbeat',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
