# Generated by Django 5.2.17 on 2026-09-10 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0010_job_heartbeat_shared'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='ocr_confidence',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='ocr_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='parse_checks',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='invoice',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='receipts/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ShopItemPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price_ttc', models.DecimalField(decimal_places=2, help_text="Prix unitaire TTC tel qu'imprimé sur le ticket.", max_digits=10)),
                ('label', models.CharField(help_text='Le produit correspondant à ce prix.', max_length=255)),
                ('valid_from', models.DateField(blank=True, help_text="À partir de quand ce prix s'applique. Vide = depuis toujours.", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_prices', to='invoices.supplier')),
            ],
            options={
                'ordering': ['supplier', 'unit_price_ttc', '-valid_from'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('valid_from', None), _negated=True), fields=('supplier', 'unit_price_ttc', 'valid_from'), name='unique_shop_item_price_dated'), models.UniqueConstraint(condition=models.Q(('valid_from', None)), fields=('supplier', 'unit_price_ttc'), name='unique_shop_item_price_undated')],
            },
        ),
    ]
