# Generated by Django 5.2.17 on 2026-09-15 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0014_backfill_receipt_hashes'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceline',
            name='read_as',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
