# Generated by Django 5.2.17 on 2026-09-17 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0019_supplier_ticket_header'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceline',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=12),
        ),
    ]
