# Generated by Django 5.2.17 on 2026-09-17 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0020_invoice_line_decimal_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='ticket_identifiers',
            field=models.JSONField(blank=True, default=list, verbose_name='identifiants lus sur ses documents'),
        ),
    ]
