# Generated by Django 5.2.17 on 2026-09-17 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0021_supplier_ticket_identifiers'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='source_text',
            field=models.TextField(blank=True),
        ),
    ]
