# Generated by Django 5.2.17 on 2026-09-18 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0024_forget_replaced_parsers'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='vat_breakdown',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
