# Generated by Django 5.2.17 on 2026-09-18 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0025_invoice_vat_breakdown'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteInvoiceSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_url', models.URLField(help_text="La page où l'on se connecte.", max_length=500)),
                ('username_env', models.CharField(help_text="Nom de la variable du fichier .env qui contient l'identifiant (ex. FREEBOX_LOGIN).", max_length=64)),
                ('password_env', models.CharField(help_text='Nom de la variable du fichier .env qui contient le mot de passe (ex. FREEBOX_PASSWORD).', max_length=64)),
                ('invoices_url', models.URLField(blank=True, help_text='La page qui liste les factures, une fois connecté. Vide : le lien « Factures » de la page est suivi.', max_length=500)),
                ('navigation', models.TextField(blank=True, help_text="Liens à suivre dans l'ordre après la connexion, un texte par ligne (ex. « Conso et factures »). Vide : le premier lien qui parle de factures.")),
                ('username_selector', models.CharField(blank=True, help_text='Sélecteur CSS du champ identifiant (vide : trouvé seul).', max_length=300)),
                ('password_selector', models.CharField(blank=True, help_text='Sélecteur CSS du champ mot de passe (vide : trouvé seul).', max_length=300)),
                ('submit_selector', models.CharField(blank=True, help_text='Sélecteur CSS du bouton de connexion (vide : trouvé seul).', max_length=300)),
                ('link_selector', models.CharField(blank=True, help_text='Sélecteur CSS des liens ou boutons qui téléchargent une facture (vide : ceux qui mènent à un PDF ou disent « Télécharger »).', max_length=300)),
                ('next_selector', models.CharField(blank=True, help_text="Sélecteur CSS du bouton « page suivante » (vide : « Suivant », « Voir plus »… s'il y en a un).", max_length=300)),
                ('show_browser', models.BooleanField(default=False, help_text='Ouvrir la fenêtre du navigateur : pour un site qui demande un code reçu par SMS ou un captcha, à saisir vous-même pendant la récupération.')),
                ('invoice_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='website_source', to='invoices.invoicetype')),
            ],
        ),
    ]
