# Generated by Django 5.2.17 on 2026-09-18 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0027_supplier_scrape_pause'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='refused_identifiers',
            field=models.JSONField(blank=True, default=list, verbose_name='identifiants écartés à la main'),
        ),
        migrations.CreateModel(
            name='SupplierChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('CREATED', 'Création'), ('RENAMED', 'Nom'), ('HEADER', 'En-tête'), ('IDENTIFIERS', 'Identifiants'), ('CHARGES', 'Nature'), ('SPLIT', 'Séparation'), ('TYPES', 'Types de factures'), ('FIRST_DOCUMENT', 'Premier document')], max_length=20)),
                ('summary', models.TextField()),
                ('cause', models.CharField(blank=True, max_length=255)),
                ('by_person', models.BooleanField(default=False)),
                ('needs_review', models.BooleanField(default=False)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('operation', models.UUIDField(blank=True, db_index=True, null=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('undone_at', models.DateTimeField(blank=True, null=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='invoices.invoice')),
                ('other_supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='invoices.supplier')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='invoices.supplier')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
    ]
