# Generated by Django 5.2.17 on 2026-09-18 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0028_supplier_changes'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='supplier_doubt',
            field=models.TextField(blank=True, default=''),
        ),
    ]
