# Generated by Django 5.2.17 on 2026-09-18 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0029_invoice_supplier_doubt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierchange',
            name='kind',
            field=models.CharField(choices=[('CREATED', 'Création'), ('RENAMED', 'Nom'), ('HEADER', 'En-tête'), ('IDENTIFIERS', 'Identifiants'), ('CHARGES', 'Nature'), ('TYPES', 'Types de factures'), ('FIRST_DOCUMENT', 'Premier document')], max_length=20),
        ),
    ]
