# Generated by Django 5.2.17 on 2026-09-19 11:25
"""Whether a document's VAT table is one a person saved (Invoice.
vat_table_typed) - and, for the documents already validated, since when
that can be said: every document validated since the table was on the
review page (the backup « …pre_vat_table », 18/09 at 03:22 in Paris) was
validated through a page that posted its table, even empty. Three of them
(765, 842, 893 on 19/09) were saved with it emptied, and were being given
the reading's back."""

from datetime import datetime, timezone

from django.db import migrations, models

#: When the VAT table shipped on the review page, in UTC.
TABLE_SHIPPED = datetime(2026, 9, 18, 1, 22, tzinfo=timezone.utc)


def mark_typed_tables(apps, schema_editor):
    Invoice = apps.get_model("invoices", "Invoice")
    Invoice.objects.filter(reviewed_at__gte=TABLE_SHIPPED).update(vat_table_typed=True)


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0030_remove_split_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='vat_table_typed',
            field=models.BooleanField(default=False, help_text="La table de TVA est celle qu'une personne a enregistrée, même vide : elle n'est plus relue."),
        ),
        migrations.RunPython(mark_typed_tables, migrations.RunPython.noop),
    ]
