# Generated by Django 5.2.17 on 2026-09-25 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0033_invoice_adjustment_vat_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceline',
            name='is_spread_charge',
            field=models.BooleanField(default=False, help_text="Cette ligne n'est pas un produit : son montant est réparti sur les autres lignes de la facture.", verbose_name='frais à répartir'),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='spread_ht',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
