# Generated by Django 5.2.17 on 2026-09-25 13:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0034_invoiceline_is_spread_charge_invoiceline_spread_ht"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplier",
            name="typed_identifiers",
            field=models.JSONField(blank=True, default=list, verbose_name="identifiants saisis à la main"),
        ),
    ]
