# Generated by Django 5.2.17 on 2026-10-02 16:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0035_supplier_typed_identifiers"),
    ]

    operations = [
        migrations.AddField(
            model_name="receiptbatch",
            name="sent_by",
            field=models.CharField(blank=True, db_index=True, max_length=150, verbose_name="envoyé par"),
        ),
    ]
