# Generated by Django 5.2.17 on 2026-10-02 13:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0036_receiptbatch_sent_by"),
    ]

    operations = [
        migrations.CreateModel(
            name="AutoGather",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=80, verbose_name="nom")),
                ("sources", models.JSONField(blank=True, default=list, verbose_name="sources")),
                ("weekdays", models.CharField(max_length=14, verbose_name="jours")),
                ("start_time", models.TimeField(verbose_name="à partir de")),
                ("end_time", models.TimeField(verbose_name="jusqu'à")),
                (
                    "every_minutes",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (15, "15 min"),
                            (30, "30 min"),
                            (60, "1 h"),
                            (120, "2 h"),
                            (180, "3 h"),
                            (240, "4 h"),
                            (360, "6 h"),
                            (720, "12 h"),
                        ],
                        default=60,
                        verbose_name="toutes les",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="actif")),
                ("last_slot_at", models.DateTimeField(blank=True, null=True)),
                ("last_result", models.CharField(blank=True, max_length=200)),
                ("last_failed_codes", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["pk"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("end_time__gte", models.F("start_time"))),
                        name="auto_gather_end_after_start",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="GatherCoverage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=40, unique=True)),
                ("searched_until", models.DateField(blank=True, null=True)),
                ("pending_from", models.DateField(blank=True, null=True)),
                ("pending_until", models.DateField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.AddField(
            model_name="scrapejob",
            name="auto_gather_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="scrapejob",
            name="trigger",
            field=models.CharField(
                choices=[("manual", "à la main"), ("automatic", "automatique")], default="manual", max_length=10
            ),
        ),
    ]
