from django.urls import path

from . import views

app_name = "inventory"

urlpatterns = [
    path("", views.StockListView.as_view(), name="stock_list"),
    path("liste/", views.stock_catalogue, name="stock_catalogue"),
    path("stock-types/new/", views.StockTypeCreateView.as_view(), name="stock_type_create"),
    path("stock-types/<int:pk>/edit/", views.StockTypeUpdateView.as_view(), name="stock_type_update"),
    path("stock-types/<int:pk>/merge/", views.merge_stock_type, name="stock_type_merge"),
    path("stock-types/<int:pk>/delete/", views.delete_stock_type, name="stock_type_delete"),
    path("stock-types/<int:pk>/movements/", views.stock_type_movements, name="stock_type_movements"),
    path("stock-types/<int:pk>/price-history/", views.stock_type_price_history, name="stock_type_price_history"),
    path("stock-types/clear-empty/", views.clear_empty_stock_types, name="clear_empty_stock_types"),
    path("search/", views.search_stock_types, name="search_stock_types"),
    path("export-associations/", views.export_associations, name="export_associations"),
    path("import-associations/", views.import_associations, name="import_associations"),
    path("products/<int:product_id>/remove/", views.remove_product, name="remove_product"),
    path("products/<int:product_id>/edit-conversion/", views.edit_product_conversion, name="edit_product_conversion"),
    path("charges/<int:product_id>/documents/", views.charge_documents, name="charge_documents"),
    path("charges/<int:product_id>/historique/", views.charge_history, name="charge_history"),
    path(
        "charges/fournisseur/<int:supplier_id>/documents/",
        views.charge_supplier_documents,
        name="charge_supplier_documents",
    ),
    path(
        "charges/fournisseur/<int:supplier_id>/historique/",
        views.charge_supplier_history,
        name="charge_supplier_history",
    ),
    path("courses/", views.shopping_list, name="shopping_list"),
    path("courses/rythme/", views.shopping_rhythm, name="shopping_rhythm"),
    path("courses/reglages/", views.shopping_settings, name="shopping_settings"),
    path("courses/exclure/", views.shopping_exclude, name="shopping_exclude"),
    path("courses/reinclure/", views.shopping_include, name="shopping_include"),
    path("courses/listes/", views.shopping_lists, name="shopping_lists"),
    path("courses/liste/", views.shopping_list_page, name="shopping_list_page"),
    path("courses/liste/ajouter/", views.shopping_list_add, name="shopping_list_add"),
    path("courses/liste/tout-ajouter/", views.shopping_list_add_all, name="shopping_list_add_all"),
    path("courses/liste/modifier/", views.shopping_list_item_edit, name="shopping_list_item_edit"),
    path("courses/liste/retirer/", views.shopping_list_item_delete, name="shopping_list_item_delete"),
    path("courses/liste/cocher/", views.shopping_list_item_tick, name="shopping_list_item_tick"),
    path("courses/liste/terminer/", views.shopping_list_finish, name="shopping_list_finish"),
    path("courses/liste/vider/", views.shopping_list_clear, name="shopping_list_clear"),
    path("review/", views.review_queue, name="review_queue"),
    path("review/approve-all/", views.approve_all_suggestions, name="approve_all_suggestions"),
    path("review/<int:product_id>/assign/", views.assign_product, name="assign_product"),
    path("stock-takes/", views.StockTakeListView.as_view(), name="stock_take_list"),
    path("stock-takes/new/", views.stock_take_create, name="stock_take_create"),
    path("stock-takes/value-line/", views.value_stock_take_line, name="value_stock_take_line"),
    path("stock-takes/fill-gaps/", views.stock_gap_filler, name="stock_gap_filler"),
    path("stock-takes/fill-gaps/add/", views.stock_gap_filler_add, name="stock_gap_filler_add"),
    path("stock-takes/fill-gaps/undo/", views.stock_gap_filler_undo, name="stock_gap_filler_undo"),
    path("stock-takes/fill-gaps/clear/", views.stock_gap_filler_clear, name="stock_gap_filler_clear"),
    path("stock-takes/fill-gaps/exclude/", views.stock_gap_filler_exclude, name="stock_gap_filler_exclude"),
    path("stock-takes/fill-gaps/include/", views.stock_gap_filler_include, name="stock_gap_filler_include"),
    path("stock-takes/fill-gaps/recent/", views.stock_gap_filler_recent, name="stock_gap_filler_recent"),
    path("stock-takes/<int:pk>/", views.stock_take_detail, name="stock_take_detail"),
    path("stock-takes/<int:pk>/edit/", views.stock_take_update, name="stock_take_update"),
    path("stock-takes/<int:pk>/variance/", views.stock_take_variance, name="stock_take_variance"),
    path("stock-takes/<int:pk>/delete/", views.stock_take_delete, name="stock_take_delete"),
]
