# Generated by Django 5.2.17 on 2026-09-27 21:09

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import staff.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("last_name", models.CharField(max_length=100, verbose_name="nom")),
                ("first_name", models.CharField(blank=True, max_length=100, verbose_name="prénom")),
                ("is_active", models.BooleanField(default=True, verbose_name="actif")),
                (
                    "monday_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal("0"), message="Les heures ne peuvent pas être négatives."
                            ),
                            django.core.validators.MaxValueValidator(
                                Decimal("24"), message="Pas plus de 24 h dans une journée."
                            ),
                        ],
                        verbose_name="lundi",
                    ),
                ),
                (
                    "tuesday_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal("0"), message="Les heures ne peuvent pas être négatives."
                            ),
                            django.core.validators.MaxValueValidator(
                                Decimal("24"), message="Pas plus de 24 h dans une journée."
                            ),
                        ],
                        verbose_name="mardi",
                    ),
                ),
                (
                    "wednesday_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal("0"), message="Les heures ne peuvent pas être négatives."
                            ),
                            django.core.validators.MaxValueValidator(
                                Decimal("24"), message="Pas plus de 24 h dans une journée."
                            ),
                        ],
                        verbose_name="mercredi",
                    ),
                ),
                (
                    "thursday_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal("0"), message="Les heures ne peuvent pas être négatives."
                            ),
                            django.core.validators.MaxValueValidator(
                                Decimal("24"), message="Pas plus de 24 h dans une journée."
                            ),
                        ],
                        verbose_name="jeudi",
                    ),
                ),
                (
                    "friday_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal("0"), message="Les heures ne peuvent pas être négatives."
                            ),
                            django.core.validators.MaxValueValidator(
                                Decimal("24"), message="Pas plus de 24 h dans une journée."
                            ),
                        ],
                        verbose_name="vendredi",
                    ),
                ),
                (
                    "saturday_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal("0"), message="Les heures ne peuvent pas être négatives."
                            ),
                            django.core.validators.MaxValueValidator(
                                Decimal("24"), message="Pas plus de 24 h dans une journée."
                            ),
                        ],
                        verbose_name="samedi",
                    ),
                ),
                (
                    "sunday_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal("0"), message="Les heures ne peuvent pas être négatives."
                            ),
                            django.core.validators.MaxValueValidator(
                                Decimal("24"), message="Pas plus de 24 h dans une journée."
                            ),
                        ],
                        verbose_name="dimanche",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "salarié",
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="Establishment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(blank=True, max_length=255, verbose_name="nom de l'établissement")),
                ("address", models.TextField(blank=True, verbose_name="adresse")),
            ],
            options={
                "verbose_name": "établissement",
            },
        ),
        migrations.CreateModel(
            name="Timesheet",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("month", models.DateField(validators=[staff.models.validate_first_of_month], verbose_name="mois")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="timesheets", to="staff.employee"
                    ),
                ),
            ],
            options={
                "verbose_name": "fiche de temps",
                "verbose_name_plural": "fiches de temps",
                "ordering": ["-month"],
            },
        ),
        migrations.CreateModel(
            name="TimesheetDay",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField()),
                (
                    "hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal("0"), message="Les heures ne peuvent pas être négatives."
                            ),
                            django.core.validators.MaxValueValidator(
                                Decimal("24"), message="Pas plus de 24 h dans une journée."
                            ),
                        ],
                        verbose_name="heures",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("travail", "Travail"),
                            ("repos", "Repos"),
                            ("conges", "Congés payés"),
                            ("repos_comp", "Repos compensateur"),
                            ("ferie", "Férié chômé"),
                            ("maladie", "Arrêt maladie"),
                            ("absence", "Absence"),
                        ],
                        default="travail",
                        max_length=12,
                        verbose_name="motif",
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=255, verbose_name="note")),
                (
                    "timesheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="days", to="staff.timesheet"
                    ),
                ),
            ],
            options={
                "verbose_name": "jour",
                "ordering": ["date"],
            },
        ),
        migrations.AddConstraint(
            model_name="timesheet",
            constraint=models.UniqueConstraint(fields=("employee", "month"), name="unique_timesheet_per_month"),
        ),
        migrations.AddConstraint(
            model_name="timesheetday",
            constraint=models.UniqueConstraint(fields=("timesheet", "date"), name="unique_timesheet_day"),
        ),
        migrations.AddConstraint(
            model_name="timesheetday",
            constraint=models.CheckConstraint(
                condition=models.Q(("kind", "travail"), ("hours", 0), _connector="OR"),
                name="timesheet_day_hours_only_when_worked",
            ),
        ),
        migrations.AddConstraint(
            model_name="timesheetday",
            constraint=models.CheckConstraint(
                condition=models.Q(("hours__gte", 0), ("hours__lte", 24)), name="timesheet_day_hours_within_a_day"
            ),
        ),
    ]
