# Generated by Django 5.2.17 on 2026-09-15 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoices', '0015_invoiceline_read_as'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(blank=True, max_length=40)),
                ('operation_date', models.DateField()),
                ('value_date', models.DateField(blank=True, null=True)),
                ('card_date', models.DateField(blank=True, null=True)),
                ('bank_type', models.CharField(blank=True, max_length=80)),
                ('kind', models.CharField(choices=[('CARD', 'Carte'), ('DEBIT', 'Prélèvement'), ('TRANSFER', 'Virement'), ('OTHER', 'Autre')], default='OTHER', max_length=10)),
                ('label', models.TextField()),
                ('counterparty', models.CharField(blank=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fingerprint', models.CharField(max_length=64, unique=True)),
                ('no_invoice', models.BooleanField(default=False)),
                ('settled_by_hand', models.BooleanField(default=False)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-operation_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='InvoicePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('AUTO', 'Automatique'), ('MANUAL', 'À la main')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='invoices.invoice')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='bank.banktransaction')),
            ],
            options={
                'ordering': ['invoice__invoice_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CounterpartyAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_aliases', to='invoices.supplier')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('supplier', 'name'), name='unique_supplier_bank_alias')],
            },
        ),
    ]
