# Generated by Django 5.2.17 on 2026-09-28 13:13

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nom du bar')),
                ('dir_name', models.CharField(help_text="Nom du dossier de l'espace sous TENANTS_ROOT : tiré au hasard, jamais le nom du bar.", max_length=40, unique=True, validators=[django.core.validators.RegexValidator('^[a-z0-9][a-z0-9-]{2,39}$')], verbose_name='dossier')),
                ('uses_server_integrations', models.BooleanField(default=False, help_text="Metro, la boîte aux lettres, L'Addition, l'analyse IA et les portails du fichier .env.", verbose_name='utilise les accès du serveur')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='créé le')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
            ],
            options={
                'verbose_name': 'espace',
                'verbose_name_plural': 'espaces',
                'ordering': ['name', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(max_length=64, unique=True)),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='note')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='créée le')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='expire le')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='utilisée le')),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='utilisée par')),
            ],
            options={
                'verbose_name': 'invitation',
                'verbose_name_plural': 'invitations',
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='SigningLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signing_links', to='accounts.tenant')),
            ],
            options={
                'verbose_name': 'lien de signature',
                'verbose_name_plural': 'liens de signature',
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Propriétaire'), ('member', 'Membre')], default='owner', max_length=10, verbose_name='rôle')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='depuis le')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='accounts.tenant')),
            ],
            options={
                'verbose_name': 'membre',
                'verbose_name_plural': 'membres',
                'constraints': [models.UniqueConstraint(fields=('user', 'tenant'), name='accounts_one_membership_per_espace')],
            },
        ),
    ]
