# Generated by Django 5.2.17 on 2026-10-02 16:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

#: accounts.access.AREAS as this migration found them: a membership that was
#: already a MEMBER opened every page but the owner's, and still does.
AREAS_IN_0003 = [
    "invoices_add",
    "stock_takes",
    "returnables",
    "invoices",
    "stock_gaps",
    "products",
    "recipes",
    "bank",
    "margins",
    "staff",
]


def keep_what_members_opened(apps, schema_editor):
    Membership = apps.get_model("accounts", "Membership")
    Membership.objects.using(schema_editor.connection.alias).filter(role="member").update(pages=AREAS_IN_0003)


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_invitation_refused_addresses"),
    ]

    operations = [
        migrations.AddField(
            model_name="membership",
            name="pages",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Pour un employé : les pages que le propriétaire lui ouvre (accounts/access.py).",
                verbose_name="pages ouvertes",
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="role",
            field=models.CharField(
                choices=[("owner", "Propriétaire"), ("member", "Employé")],
                default="owner",
                max_length=10,
                verbose_name="rôle",
            ),
        ),
        migrations.CreateModel(
            name="MemberInvitation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("token_hash", models.CharField(max_length=64, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, verbose_name="créée le")),
                ("expires_at", models.DateTimeField(verbose_name="expire le")),
                (
                    "membership",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitation",
                        to="accounts.membership",
                    ),
                ),
            ],
            options={
                "verbose_name": "invitation d'employé",
                "verbose_name_plural": "invitations d'employés",
            },
        ),
        migrations.RunPython(keep_what_members_opened, migrations.RunPython.noop),
    ]
