# Generated by Django 5.2.17 on 2026-10-02 12:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_member_pages_and_invitations"),
    ]

    operations = [
        migrations.CreateModel(
            name="PushDevice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("endpoint", models.URLField(max_length=2048, unique=True, verbose_name="adresse de notification")),
                ("p256dh", models.CharField(max_length=100)),
                ("auth", models.CharField(max_length=40)),
                ("server_key", models.CharField(max_length=100, verbose_name="clé du serveur")),
                ("label", models.CharField(max_length=80, verbose_name="appareil")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, verbose_name="inscrit le")),
                ("seen_at", models.DateTimeField(default=django.utils.timezone.now, verbose_name="vu le")),
                ("last_success_at", models.DateTimeField(blank=True, null=True, verbose_name="dernier envoi réussi")),
                ("last_error_at", models.DateTimeField(blank=True, null=True, verbose_name="dernière erreur le")),
                ("gone_at", models.DateTimeField(blank=True, null=True, verbose_name="désinscrit par le service le")),
                ("logged_out_at", models.DateTimeField(blank=True, null=True, verbose_name="déconnecté le")),
                ("last_error", models.CharField(blank=True, max_length=200, verbose_name="dernière erreur")),
                ("failures", models.PositiveIntegerField(default=0, verbose_name="échecs de suite")),
                (
                    "membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="push_devices",
                        to="accounts.membership",
                        verbose_name="membre",
                    ),
                ),
            ],
            options={
                "verbose_name": "appareil",
                "verbose_name_plural": "appareils",
                "ordering": ["-seen_at", "-pk"],
            },
        ),
    ]
