# Generated by Django 5.2.17 on 2026-08-31 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='invoices.supplier'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='invoice_line',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movement', to='invoices.invoiceline'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='stock_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.stocktype'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='inventory.stocktype'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('supplier', 'raw_name'), name='unique_product_per_supplier'),
        ),
    ]
