# Generated by Django 5.2.17 on 2026-08-31 13:06

from decimal import Decimal
from django.db import migrations, models


def backfill_product_unit(apps, schema_editor):
    """Already-reviewed products don't have `unit` set yet. Reproduce exactly
    what was already computed for their existing StockMovements: if
    stock_equivalent was set (the bottle/pack conversion feature), the
    product was quantity-based (unit=UNIT); otherwise it was using
    stock_type.unit + total_volume directly (equivalent to unit=stock_type's
    unit, stock_equivalent=1). This needs to run before stock_equivalent
    becomes non-nullable below, while we can still tell "never set" (None)
    apart from "explicitly set to some value".
    """
    Product = apps.get_model("inventory", "Product")
    for product in Product.objects.filter(stock_type__isnull=False).select_related("stock_type"):
        if product.stock_equivalent is not None:
            product.unit = "UNIT"
        else:
            product.unit = product.stock_type.unit
            product.stock_equivalent = Decimal("1")
        product.save(update_fields=["unit", "stock_equivalent"])


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_fix_weight_based_unit_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='unit_label',
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('L', 'Litre'), ('UNIT', 'Unité'), ('KG', 'Kilogramme')], default='UNIT', max_length=4),
        ),
        migrations.RunPython(backfill_product_unit, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='product',
            name='stock_equivalent',
            field=models.DecimalField(decimal_places=4, default=Decimal('1'), help_text="How much of the stock type's unit is in one 'unit' of this product.", max_digits=10),
        ),
        migrations.AlterField(
            model_name='stocktype',
            name='unit',
            field=models.CharField(choices=[('L', 'Litre'), ('UNIT', 'Unité'), ('KG', 'Kilogramme')], max_length=4),
        ),
    ]
