# Generated by Django 5.2.17 on 2026-08-31 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_product_unit_label_product_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ai_suggestion',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
