# Generated by Django 5.2.17 on 2026-08-31 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_suggestionjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestionjob',
            name='cancel_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='suggestionjob',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('RUNNING', 'En cours'), ('SUCCESS', 'Terminé'), ('FAILED', 'Échoué'), ('CANCELLED', 'Annulé')], default='PENDING', max_length=20),
        ),
    ]
