# Generated by Django 5.2.17 on 2026-09-02 02:01

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_suggestionjob_cancel_requested_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taken_at', models.DateTimeField()),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-taken_at'],
            },
        ),
        migrations.CreateModel(
            name='StockTakeLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counted_quantity', models.DecimalField(decimal_places=4, max_digits=10)),
                ('value_ht', models.DecimalField(decimal_places=2, max_digits=10)),
                ('has_shortfall', models.BooleanField(default=False)),
                ('shortfall_quantity', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_take_lines', to='inventory.product')),
                ('stock_take', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.stocktake')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('stock_take', 'product'), name='unique_product_per_stock_take')],
            },
        ),
    ]
