# Generated by Django 5.2.17 on 2026-09-02 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_stocktake_stocktakeline'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='stocktakeline',
            name='unique_product_per_stock_take',
        ),
        migrations.AddField(
            model_name='stocktakeline',
            name='stock_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_take_lines', to='inventory.stocktype'),
        ),
        migrations.AlterField(
            model_name='stocktakeline',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_take_lines', to='inventory.product'),
        ),
        migrations.AddConstraint(
            model_name='stocktakeline',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('product__isnull', False), ('stock_type__isnull', True)), models.Q(('product__isnull', True), ('stock_type__isnull', False)), _connector='OR'), name='stocktakeline_exactly_one_source'),
        ),
        migrations.AddConstraint(
            model_name='stocktakeline',
            constraint=models.UniqueConstraint(condition=models.Q(('product__isnull', False)), fields=('stock_take', 'product'), name='unique_product_per_stock_take'),
        ),
        migrations.AddConstraint(
            model_name='stocktakeline',
            constraint=models.UniqueConstraint(condition=models.Q(('stock_type__isnull', False)), fields=('stock_take', 'stock_type'), name='unique_stock_type_per_stock_take'),
        ),
    ]
