# Generated by Django 5.2.17 on 2026-09-02 10:19

import django.db.models.deletion
from django.db import migrations, models


def backfill_unit(apps, schema_editor):
    """Existing rows were saved before StockTakeLine.unit existed, when the
    unit was auto-detected (see services.product_is_discrete_count) rather
    than stored - so a stock-type line was always in that stock type's own
    unit, and a product line was in "Unité" unless the product's own
    invoice history showed a genuinely variable (not a fixed bottle/pack
    size) total_volume. Re-derive that same choice here rather than
    leaving every row at the "UNIT" placeholder the AddField above used,
    so a pre-existing measured-product line doesn't end up mislabeled.
    """
    StockTakeLine = apps.get_model("inventory", "StockTakeLine")
    InvoiceLine = apps.get_model("invoices", "InvoiceLine")

    for line in StockTakeLine.objects.select_related("product__stock_type", "stock_type").all():
        if line.stock_type_id:
            line.unit = line.stock_type.unit
        else:
            ratios = {
                total_volume / quantity
                for total_volume, quantity in InvoiceLine.objects.filter(
                    product_id=line.product_id, total_volume__isnull=False, quantity__gt=0
                ).values_list("total_volume", "quantity")
            }
            is_discrete = len(ratios) <= 1
            line.unit = "UNIT" if is_discrete else line.product.stock_type.unit
        line.save(update_fields=["unit"])


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_remove_stocktakeline_unique_product_per_stock_take_and_more'),
        ('invoices', '0004_invoiceline_colisage'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktakeline',
            name='unit',
            field=models.CharField(choices=[('L', 'Litre'), ('UNIT', 'Unité'), ('KG', 'Kilogramme')], default='UNIT', max_length=4),
            preserve_default=False,
        ),
        migrations.RunPython(backfill_unit, migrations.RunPython.noop),
        migrations.CreateModel(
            name='StockTakeLineSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_used', models.DecimalField(decimal_places=4, max_digits=10)),
                ('unit_cost_ht', models.DecimalField(decimal_places=4, max_digits=10)),
                ('invoice_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='invoices.invoiceline')),
                ('stock_take_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='inventory.stocktakeline')),
            ],
            options={
                'ordering': ['-invoice_line__invoice__invoice_date'],
            },
        ),
    ]
