# Generated by Django 5.2.17 on 2026-09-02 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_stocktakeline_unit_stocktakelinesource'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='kind',
            field=models.CharField(choices=[('PURCHASE', 'Achat'), ('LOSS', 'Perte connue'), ('CORRECTION', 'Correction')], default='PURCHASE', max_length=12),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='occurred_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
