# Generated by Django 5.2.17 on 2026-09-03 10:28

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_stockmovement_kind_stockmovement_occurred_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock_equivalent',
            field=models.DecimalField(decimal_places=4, default=Decimal('1'), help_text="Quantité de l'unité du type de stock contenue dans une « unité » de ce produit.", max_digits=10),
        ),
    ]
