# Generated by Django 5.2.17 on 2026-09-20 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_stocktype_count_in_products_margin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktype',
            name='count_in_products_margin',
            field=models.BooleanField(default=False, help_text="Coché, ce qui en a été acheté sur la période compte dans la marge produits : l'essuie-tout, les gobelets, les pailles ne sont dans aucune recette, donc rien ne les sort du stock quand une vente est tapée et leurs achats sont la seule mesure qu'il y ait. À ne pas cocher pour un article qui sert déjà dans une recette : il serait compté deux fois, et la page Marges le dit.", verbose_name='compter dans la marge produits'),
        ),
    ]
