# Generated by Django 5.2.17 on 2026-10-01 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0017_alter_stocktype_count_in_products_margin"),
    ]

    operations = [
        migrations.CreateModel(
            name="GapFillEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("total", models.DecimalField(decimal_places=2, max_digits=10)),
                ("reason", models.CharField(blank=True, max_length=32)),
                ("lines", models.JSONField(blank=True, default=list)),
                ("sales_up_to", models.DateField(blank=True, null=True)),
                ("sales_from", models.DateField(blank=True, null=True)),
                ("sales_seen", models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "stock_take",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gap_fill_entries",
                        to="inventory.stocktake",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "pk"],
            },
        ),
    ]
