# Generated by Django 5.2.17 on 2026-10-01 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0018_gap_fill_entry"),
    ]

    operations = [
        migrations.CreateModel(
            name="GapExclusion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("category", models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "stock_type",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gap_exclusion",
                        to="inventory.stocktype",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("stock_type__isnull", False), ("category__isnull", True)),
                            models.Q(("stock_type__isnull", True), ("category__isnull", False)),
                            _connector="OR",
                        ),
                        name="gap_exclusion_article_or_category",
                    )
                ],
            },
        ),
    ]
