# Generated by Django 5.2.17 on 2026-10-01 13:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0019_gap_exclusion"),
    ]

    operations = [
        migrations.CreateModel(
            name="GapFillSetting",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sold_within_months", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(condition=models.Q(("id", 1)), name="gap_fill_setting_one_row"),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("sold_within_months__isnull", True),
                            models.Q(("sold_within_months__gte", 1), ("sold_within_months__lte", 120)),
                            _connector="OR",
                        ),
                        name="gap_fill_setting_months_in_range",
                    ),
                ],
            },
        ),
    ]
