# Generated by Django 5.2.17 on 2026-10-04 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0020_gap_fill_setting"),
        ("invoices", "0037_auto_gather"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShoppingSetting",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("threshold_percent", models.PositiveSmallIntegerField(default=25)),
                ("memory_months", models.PositiveSmallIntegerField(default=6)),
                ("use_till", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(condition=models.Q(("id", 1)), name="shopping_setting_one_row"),
                    models.CheckConstraint(
                        condition=models.Q(("threshold_percent__gte", 10), ("threshold_percent__lte", 60)),
                        name="shopping_setting_threshold_in_range",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("memory_months__gte", 2), ("memory_months__lte", 24)),
                        name="shopping_setting_memory_in_range",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ShoppingExclusion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("category", models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "stock_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shopping_exclusions",
                        to="inventory.stocktype",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shopping_exclusions",
                        to="invoices.supplier",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("stock_type__isnull", False), ("category__isnull", True)),
                            models.Q(("stock_type__isnull", True), ("category__isnull", False)),
                            _connector="OR",
                        ),
                        name="shopping_exclusion_article_or_category",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("category__isnull", True), ("supplier__isnull", True), _connector="OR"),
                        name="shopping_exclusion_category_everywhere",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("supplier__isnull", True)),
                        fields=("stock_type",),
                        name="shopping_exclusion_article_once",
                    ),
                    models.UniqueConstraint(
                        fields=("stock_type", "supplier"), name="shopping_exclusion_article_once_per_store"
                    ),
                ],
            },
        ),
    ]
