# Generated by Django 5.2.17 on 2026-09-02 00:58

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0008_suggestionjob_cancel_requested_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('yield_quantity', models.DecimalField(decimal_places=4, default=Decimal('1'), help_text='Quantité produite par une préparation complète de cette recette.', max_digits=10)),
                ('yield_unit', models.CharField(choices=[('L', 'Litre'), ('UNIT', 'Unité'), ('KG', 'Kilogramme')], default='UNIT', max_length=4)),
                ('selling_price_ttc', models.DecimalField(decimal_places=2, help_text='Prix de vente affiché (TTC).', max_digits=8)),
                ('vat_rate', models.DecimalField(decimal_places=3, default=Decimal('0.20'), help_text='Ex : 0.20 pour 20%.', max_digits=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=10)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipes.recipe')),
                ('stock_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.stocktype')),
                ('sub_recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='used_in', to='recipes.recipe')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('stock_type__isnull', False), ('sub_recipe__isnull', True)), models.Q(('stock_type__isnull', True), ('sub_recipe__isnull', False)), _connector='OR'), name='recipeingredient_exactly_one_source')],
            },
        ),
    ]
