# Generated by Django 5.2.17 on 2026-09-02 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_category_recipe_happy_hour_price_ttc_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipeingredient',
            options={'ordering': ['group', 'id']},
        ),
    ]
