# Generated by Django 5.2.17 on 2026-09-02 21:29

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipeingredient_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='happy_hour_price_ttc',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optionnel - prix TTC en happy hour.', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='selling_price_ttc',
            field=models.DecimalField(decimal_places=2, help_text='Prix de vente affiché (TTC).', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='vat_rate',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.20'), help_text='Ex : 0.20 pour 20%.', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))]),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='yield_quantity',
            field=models.DecimalField(decimal_places=4, default=Decimal('1'), help_text='Quantité produite par une préparation complète de cette recette.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))]),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='quantity',
            field=models.DecimalField(decimal_places=4, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))]),
        ),
    ]
