# Generated by Django 5.2.17 on 2026-09-03 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_recipesale'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='happy_hour_name',
            field=models.CharField(blank=True, help_text="Nom du produit en happy hour sur la caisse, s'il diffère (ex : « Alcool + soda HH »).", max_length=255),
        ),
    ]
