# Generated by Django 5.2.17 on 2026-09-03 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_salesimportjob_posproduct'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='recipesale',
            name='unique_recipe_sale_per_day',
        ),
        migrations.AddConstraint(
            model_name='recipesale',
            constraint=models.UniqueConstraint(fields=('recipe', 'sold_on', 'source'), name='unique_recipe_sale_per_day_and_source'),
        ),
    ]
