# Generated by Django 5.2.17 on 2026-09-03 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_help_text_fr'),
        ('recipes', '0008_remove_recipesale_unique_recipe_sale_per_day_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, help_text='Optionnel — votre propre numéro.', max_length=100)),
                ('sold_on', models.DateField()),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-sold_on', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleDocumentLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=10)),
                ('unit_price_ttc', models.DecimalField(blank=True, decimal_places=2, help_text='Optionnel — laissez vide pour le prix de vente de la recette.', max_digits=8, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='recipes.saledocument')),
                ('recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale_lines', to='recipes.recipe')),
                ('stock_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale_lines', to='inventory.stocktype')),
            ],
            options={
                'ordering': ['id'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('recipe__isnull', False), ('stock_type__isnull', True)), models.Q(('recipe__isnull', True), ('stock_type__isnull', False)), _connector='OR'), name='saledocumentline_exactly_one_source')],
            },
        ),
    ]
