# Generated by Django 5.2.17 on 2026-09-03 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_sale_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesimportjob',
            name='last_heartbeat',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
