# Generated by Django 5.2.17 on 2026-09-20 15:49
"""The money beside the quantities on each till day.

Every row already on file comes out at 0 € with `revenue_read` False -
« nobody has read this day's money », not « this day took 0 € ». That is
the distinction the margin pages are built on, and
`manage.py laddition_backfill_revenue --dry-run` fills them from the
exports already downloaded in scraped_invoices/, without contacting
L'Addition.
"""

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_reset_corrupted_pos_totals'),
    ]

    operations = [
        migrations.AddField(
            model_name='posproductdailyquantity',
            name='revenue_ht',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
        migrations.AddField(
            model_name='posproductdailyquantity',
            name='revenue_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='posproductdailyquantity',
            name='revenue_ttc',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
        migrations.AddField(
            model_name='posproductdailyquantity',
            name='revenue_without_rate_ttc',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
    ]
