"""A recipe that is not sold as it is has no price.

A house syrup or an infusion was filed at 0,00 € because the price was
required, and 0 is a price: its own page put that 0 against what the
preparation costs and read a margin as a loss. NULL says « pas vendue
directement » instead, and `Recipe.is_sold_directly` is the one question
anything asks - never « is it used as a sub-recipe », since most recipes
that are, are sold too.

Additive in effect: nothing is rewritten, so every recipe already filed keeps
the price it has, a 0 included. Going back means giving every NULL a price
first - the column is NOT NULL again on the way down, and there is nothing
for the reverse to invent. Measured read-only before applying: none NULL,
and the only ones at 0 had no till product and no sale.
"""

# Generated by Django 5.2.17 on 2026-09-24 22:44

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0015_recipe_sale_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="selling_price_ttc",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Prix de vente affiché (TTC). Laissez vide pour une préparation qui n'est pas vendue telle quelle : un sirop, une infusion, utilisés dans d'autres recettes.",
                max_digits=8,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
    ]
