# Generated by Django 5.2.17 on 2026-09-27 20:51
"""The till's means of payment, per day - what the bank is paid from.

A new table, empty on arrival: nothing already on file is rewritten. The
next till import fills the days it reads, and
`manage.py laddition_backfill_payments --dry-run` fills the days already
imported from the exports downloaded in scraped_invoices/, without
contacting L'Addition. Going back drops the table, and the same command
fills it again.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0016_recipe_price_optional'),
    ]

    operations = [
        migrations.CreateModel(
            name='PosDailyPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sold_on', models.DateField()),
                ('method', models.CharField(blank=True, max_length=40)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payments', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['sold_on', 'method'],
                'constraints': [models.UniqueConstraint(fields=('sold_on', 'method'), name='unique_pos_daily_payment')],
            },
        ),
    ]
