# Generated by Django 5.2.17 on 2026-10-03 02:42
"""The automatic sales imports (recipes/auto_sales.py): a new table of
rules, empty on arrival, and who started each import (`trigger`, every
existing row « à la main »; `auto_rule_id`, empty). Nothing already on file
is rewritten; going back drops the table and the two columns."""

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0017_posdailypayment"),
    ]

    operations = [
        migrations.CreateModel(
            name="AutoSalesImport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=80, verbose_name="nom")),
                ("source", models.CharField(default="laddition", max_length=40, verbose_name="source")),
                ("weekdays", models.CharField(max_length=14, verbose_name="jours")),
                ("times", models.CharField(max_length=120, verbose_name="heures")),
                ("is_active", models.BooleanField(default=True, verbose_name="actif")),
                ("last_slot_at", models.DateTimeField(blank=True, null=True)),
                ("last_result", models.CharField(blank=True, max_length=200)),
                ("last_failed", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "import automatique des ventes",
                "verbose_name_plural": "imports automatiques des ventes",
                "ordering": ["pk"],
            },
        ),
        migrations.AddField(
            model_name="salesimportjob",
            name="auto_rule_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="salesimportjob",
            name="trigger",
            field=models.CharField(
                choices=[("manual", "à la main"), ("automatic", "automatique")], default="manual", max_length=10
            ),
        ),
    ]
