# Generated by Django 5.2.17 on 2026-10-05 09:06
"""Sales invoices (« Factures de vente », recipes/sale_*.py): what a sale
document now carries - its file (media `ventes/`), its customer and stated
totals, what an electronic invoice states (number, dates, the invoice it
corrects, lines in HT with their rate, checks, the seller's SIREN), what it
counts in (`counting`) - a line tied to nothing (`label`), consumed otherwise
than invoiced (`consumed_quantity`) or rebuilt from a VAT table (`rebuilt`),
and the bank credits that pay it (`SaleDocumentPayment`).

Nothing existing changes meaning: every document counts as before
(« counted »), no line has a rate, a stated HT or a consumed quantity of its
own, and every line keeps its one source. Each existing document is given
its natural key from its content - the key « Données » gave it until now -
so an archive written before this migration still finds it.

Going back drops the new columns, the link table and every link, and puts
the old « exactly one source » constraint back: it FAILS once a line tied to
nothing exists - delete those lines first, or restore the backup."""

import hashlib
import json
from collections import defaultdict
from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import recipes.models

#: recipes.models.SALE_KEY_LENGTH, frozen.
KEY_LENGTH = 16
#: Documents written per query: SQLite caps a statement's parameters.
BATCH = 500


# The key a document had in « Données » until now, frozen here: a migration
# replays the same whatever the code becomes (bank/0006's RULES is the
# precedent). recipes/tests/test_migration_0019.py checks it against the
# live transfer.sections.sales.fingerprint and recipes.models.legacy_key.


def _fold(text):  # transfer.keys.fold, frozen
    return " ".join((text or "").split()).casefold()


def _text(value, places):  # transfer.sections.sales._text, frozen
    return None if value is None else str(Decimal(value).quantize(Decimal(1).scaleb(-places)))


def _fingerprint(reference, sold_on, note, lines):  # transfer.sections.sales.fingerprint, frozen
    canonical = {
        "reference": reference or "",
        "sold_on": sold_on.isoformat(),
        "note": note or "",
        "lines": [[kind, _fold(name), _text(quantity, 4), _text(price, 2)] for kind, name, quantity, price in lines],
    }
    return hashlib.sha256(json.dumps(canonical, sort_keys=True, ensure_ascii=False).encode("utf-8")).hexdigest()


def legacy_keys(documents) -> dict[int, str]:
    """{pk: key} for (pk, reference, sold_on, note, [(kind, name, quantity,
    price)]) given in (created_at, id) order: sha256("<fingerprint>#<occurrence>")
    cut to 16 characters - recipes.models.legacy_key. Two identical documents
    are occurrence 0 and 1, as « Données » numbers them."""
    keys = {}
    seen = defaultdict(int)
    for pk, reference, sold_on, note, lines in documents:
        fingerprint = _fingerprint(reference, sold_on, note, lines)
        keys[pk] = hashlib.sha256(f"{fingerprint}#{seen[fingerprint]}".encode()).hexdigest()[:KEY_LENGTH]
        seen[fingerprint] += 1
    return keys


def fill_keys(apps, schema_editor):
    """Every document's key from its content: its lines in id order, each
    (« recipe » or « article », the name, the quantity, the unit price) -
    every line has exactly one source here, the old constraint's. One query
    for the documents, one for the lines."""
    SaleDocument = apps.get_model("recipes", "SaleDocument")
    SaleDocumentLine = apps.get_model("recipes", "SaleDocumentLine")
    documents = list(
        SaleDocument.objects.order_by("created_at", "id").values_list("pk", "reference", "sold_on", "note")
    )
    if not documents:
        return
    lines = defaultdict(list)
    for document_id, recipe_id, recipe_name, article_name, quantity, price in SaleDocumentLine.objects.order_by(
        "id"
    ).values_list("document_id", "recipe_id", "recipe__name", "stock_type__name", "quantity", "unit_price_ttc"):
        shape = ("recipe", recipe_name) if recipe_id else ("article", article_name)
        lines[document_id].append((*shape, quantity, price))
    keys = legacy_keys((pk, reference, sold_on, note, lines[pk]) for pk, reference, sold_on, note in documents)
    SaleDocument.objects.bulk_update(
        [SaleDocument(pk=pk, key=key) for pk, key in keys.items()], ["key"], batch_size=BATCH
    )


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0018_auto_sales_import"),
        ("bank", "0008_treasury"),
    ]

    operations = [
        # 1. Words only.
        migrations.AlterField(
            model_name="saledocument",
            name="reference",
            field=models.CharField(
                blank=True, help_text="Le numéro de la facture, tel qu'imprimé.", max_length=100, verbose_name="numéro"
            ),
        ),
        migrations.AlterField(
            model_name="saledocument",
            name="sold_on",
            field=models.DateField(
                help_text="Le jour où la vente compte, dans les marges et dans le stock.", verbose_name="date de vente"
            ),
        ),
        migrations.AlterField(
            model_name="saledocumentline",
            name="quantity",
            field=models.DecimalField(decimal_places=4, max_digits=10, verbose_name="quantité facturée"),
        ),
        migrations.AlterField(
            model_name="saledocumentline",
            name="unit_price_ttc",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Vide : le prix de vente de la recette, écrit à l'enregistrement.",
                max_digits=8,
                null=True,
                verbose_name="prix unitaire TTC",
            ),
        ),
        # 2. What a document carries: every column has a default or is
        # nullable - an existing document counts, has no file and states
        # nothing.
        migrations.AddField(
            model_name="saledocument",
            name="customer",
            field=models.CharField(
                blank=True, help_text="Le client, tel qu'écrit sur la facture.", max_length=255, verbose_name="client"
            ),
        ),
        migrations.AddField(
            model_name="saledocument",
            name="customer_identifier",
            field=models.CharField(blank=True, max_length=40, verbose_name="identifiant du client"),
        ),
        migrations.AddField(
            model_name="saledocument",
            name="counting",
            field=models.CharField(
                choices=[
                    ("counted", "Compte dans les marges et le stock"),
                    ("till", "Déjà comptée par la caisse"),
                    ("deposit", "Acompte : la facture finale la comptera"),
                ],
                default="counted",
                max_length=10,
                verbose_name="compte",
            ),
        ),
        migrations.AddField(
            model_name="saledocument",
            name="stated_total_ttc",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Le total imprimé sur la facture. Vide : la somme des lignes.",
                max_digits=12,
                null=True,
                verbose_name="total TTC",
            ),
        ),
        migrations.AddField(
            model_name="saledocument",
            name="stated_total_ht",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Le total HT imprimé, à taper avec le total TTC.",
                max_digits=12,
                null=True,
                verbose_name="total HT",
            ),
        ),
        migrations.AddField(
            model_name="saledocument",
            name="prepaid_ttc",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Un acompte que la facture déduit de son total.",
                max_digits=12,
                null=True,
                verbose_name="déjà réglé",
            ),
        ),
        migrations.AddField(
            model_name="saledocument",
            name="payable_ttc",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True, verbose_name="reste à payer"
            ),
        ),
        migrations.AddField(
            model_name="saledocument",
            name="adjustment_ht",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=12, verbose_name="frais et remises (HT)"
            ),
        ),
        migrations.AddField(
            model_name="saledocument",
            name="adjustment_vat_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0")),
                    django.core.validators.MaxValueValidator(Decimal("1")),
                ],
                verbose_name="taux des frais et remises",
            ),
        ),
        migrations.AddField(
            model_name="saledocument",
            name="einvoice_format",
            field=models.CharField(blank=True, max_length=16, verbose_name="facture électronique"),
        ),
        migrations.AddField(
            model_name="saledocument",
            name="einvoice_type_code",
            field=models.CharField(blank=True, max_length=10, verbose_name="type de document"),
        ),
        migrations.AddField(
            model_name="saledocument",
            name="einvoice_issued_on",
            field=models.DateField(blank=True, null=True, verbose_name="date de la facture électronique"),
        ),
        migrations.AddField(
            model_name="saledocument",
            name="einvoice_delivered_on",
            field=models.DateField(
                blank=True,
                help_text="La date de livraison de la facture électronique, sinon le début de sa période de facturation.",
                null=True,
                verbose_name="date de livraison déclarée",
            ),
        ),
        migrations.AddField(
            model_name="saledocument",
            name="einvoice_preceding_number",
            field=models.CharField(blank=True, max_length=100, verbose_name="facture corrigée"),
        ),
        migrations.AddField(
            model_name="saledocument",
            name="einvoice_checks",
            field=models.JSONField(blank=True, default=list, verbose_name="contrôles de la facture électronique"),
        ),
        migrations.AddField(
            model_name="saledocument",
            name="seller_name",
            field=models.CharField(blank=True, max_length=255, verbose_name="vendeur"),
        ),
        migrations.AddField(
            model_name="saledocument",
            name="seller_siren",
            field=models.CharField(blank=True, db_index=True, max_length=9, verbose_name="SIREN du vendeur"),
        ),
        migrations.AddField(
            model_name="saledocument",
            name="source_file",
            field=models.FileField(blank=True, null=True, upload_to="ventes/%Y/%m/", verbose_name="fichier"),
        ),
        migrations.AddField(
            model_name="saledocument",
            name="source_sha256",
            field=models.CharField(blank=True, max_length=64, verbose_name="empreinte du fichier"),
        ),
        # 3-5. The key: added empty and NOT unique, filled from each
        # document's content, then made unique with its random default. A
        # single AddField(unique=True, default=new_sale_key) gives every
        # existing row the SAME key - Django works a callable default out
        # once for a table rebuild - and fails on the unique index with two
        # documents or more.
        migrations.AddField(
            model_name="saledocument",
            name="key",
            field=models.CharField(editable=False, max_length=16, null=True),
        ),
        migrations.RunPython(fill_keys, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="saledocument",
            name="key",
            field=models.CharField(
                default=recipes.models.new_sale_key, editable=False, max_length=16, unique=True, verbose_name="clé"
            ),
        ),
        # 6. What a line carries.
        migrations.AddField(
            model_name="saledocumentline",
            name="label",
            field=models.CharField(
                blank=True, help_text="Ce que dit la ligne de la facture.", max_length=255, verbose_name="libellé"
            ),
        ),
        migrations.AddField(
            model_name="saledocumentline",
            name="unit_price_ht",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=10, null=True, verbose_name="prix unitaire HT"
            ),
        ),
        migrations.AddField(
            model_name="saledocumentline",
            name="total_ht",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True, verbose_name="montant HT"
            ),
        ),
        migrations.AddField(
            model_name="saledocumentline",
            name="vat_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Ex : 0.20 pour 20 %.",
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0")),
                    django.core.validators.MaxValueValidator(Decimal("1")),
                ],
                verbose_name="taux de TVA",
            ),
        ),
        migrations.AddField(
            model_name="saledocumentline",
            name="consumed_quantity",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Vide : la quantité facturée. Un « Fût 30 L » vendu 1 et suivi au litre : 30.",
                max_digits=10,
                null=True,
                verbose_name="quantité consommée",
            ),
        ),
        migrations.AddField(
            model_name="saledocumentline",
            name="rebuilt",
            field=models.BooleanField(default=False, verbose_name="reconstituée"),
        ),
        # 7. A line tied to nothing; the shapes no line may take.
        migrations.RemoveConstraint(
            model_name="saledocumentline",
            name="saledocumentline_exactly_one_source",
        ),
        migrations.AddConstraint(
            model_name="saledocumentline",
            constraint=models.CheckConstraint(
                condition=models.Q(("recipe__isnull", True), ("stock_type__isnull", True), _connector="OR"),
                name="saledocumentline_at_most_one_source",
            ),
        ),
        migrations.AddConstraint(
            model_name="saledocumentline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("recipe__isnull", False),
                    ("stock_type__isnull", False),
                    models.Q(("label", ""), _negated=True),
                    _connector="OR",
                ),
                name="saledocumentline_untied_has_a_label",
            ),
        ),
        migrations.AddConstraint(
            model_name="saledocumentline",
            constraint=models.CheckConstraint(
                condition=models.Q(("total_ht__isnull", True), ("vat_rate__isnull", False), _connector="OR"),
                name="saledocumentline_ht_has_its_rate",
            ),
        ),
        migrations.AddConstraint(
            model_name="saledocumentline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("consumed_quantity__isnull", True),
                    ("recipe__isnull", False),
                    ("stock_type__isnull", False),
                    _connector="OR",
                ),
                name="saledocumentline_consumed_needs_a_source",
            ),
        ),
        migrations.AddConstraint(
            model_name="saledocumentline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("rebuilt", False),
                    models.Q(("recipe__isnull", True), ("stock_type__isnull", True)),
                    _connector="OR",
                ),
                name="saledocumentline_rebuilt_is_untied",
            ),
        ),
        # 8. One document per file; a counting the code knows.
        migrations.AddConstraint(
            model_name="saledocument",
            constraint=models.UniqueConstraint(
                condition=models.Q(("source_sha256", ""), _negated=True),
                fields=("source_sha256",),
                name="saledocument_one_per_file",
            ),
        ),
        migrations.AddConstraint(
            model_name="saledocument",
            constraint=models.CheckConstraint(
                condition=models.Q(("counting__in", ["counted", "till", "deposit"])),
                name="saledocument_counting_known",
            ),
        ),
        # 9. The bank credits that pay a document.
        migrations.CreateModel(
            name="SaleDocumentPayment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "method",
                    models.CharField(choices=[("AUTO", "Automatique"), ("MANUAL", "À la main")], max_length=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_payments",
                        to="recipes.saledocument",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sale_payments",
                        to="bank.banktransaction",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
                "constraints": [
                    models.UniqueConstraint(fields=("transaction", "document"), name="unique_transaction_sale_document")
                ],
            },
        ),
    ]
