# Generated by Django 5.2.17 on 2026-10-04 01:57
"""How a till's export is laid out (« Formats des fichiers de caisse »), and
what a sales job reads.

A new table, empty on arrival: nothing already on file is read or
rewritten, in any espace or in the _template. A bar's own till export is
then read by a format it describes; the owner's L'Addition import does not
use it. Going back drops the table (and the formats typed).

`SalesImportJob.source`: « laddition » - what every job before it read -,
or « fichier » for a till's file uploaded on « Ventes », which never counts
as L'Addition's imports for the automatic sales import
(recipes/auto_sales.py). A column with its default, no row rewritten.

Written as 0018 and renumbered after GitHub's main's 0018_auto_sales_import
(merged 04/10/2026), which it depends on: applied nowhere before.
"""

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0018_auto_sales_import"),
    ]

    operations = [
        migrations.CreateModel(
            name="TillFormat",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, unique=True, verbose_name="nom")),
                (
                    "kind",
                    models.CharField(
                        choices=[("ventes", "Ventes par produit"), ("paiements", "Encaissements")],
                        default="ventes",
                        max_length=12,
                        verbose_name="contenu",
                    ),
                ),
                (
                    "encoding",
                    models.CharField(
                        choices=[
                            ("auto", "Automatique (UTF-8, sinon Windows-1252)"),
                            ("utf-8", "UTF-8"),
                            ("cp1252", "Windows-1252"),
                            ("iso-8859-1", "ISO-8859-1"),
                            ("utf-16", "UTF-16"),
                        ],
                        default="auto",
                        max_length=12,
                        verbose_name="encodage",
                    ),
                ),
                (
                    "delimiter",
                    models.CharField(
                        choices=[
                            (";", "Point-virgule ( ; )"),
                            (",", "Virgule ( , )"),
                            ("\t", "Tabulation"),
                            ("|", "Barre verticale ( | )"),
                        ],
                        default=";",
                        max_length=2,
                        verbose_name="séparateur",
                    ),
                ),
                (
                    "decimal_mark",
                    models.CharField(
                        choices=[(",", "Virgule (1 234,56)"), (".", "Point (1,234.56)")],
                        default=",",
                        max_length=1,
                        verbose_name="séparateur décimal",
                    ),
                ),
                (
                    "date_format",
                    models.CharField(
                        choices=[
                            ("dd/mm/yyyy", "jj/mm/aaaa"),
                            ("dd/mm/yy", "jj/mm/aa"),
                            ("dd-mm-yyyy", "jj-mm-aaaa"),
                            ("dd.mm.yyyy", "jj.mm.aaaa"),
                            ("yyyy-mm-dd", "aaaa-mm-jj"),
                            ("mm/dd/yyyy", "mm/jj/aaaa"),
                        ],
                        default="dd/mm/yyyy",
                        max_length=12,
                        verbose_name="format des dates",
                    ),
                ),
                ("service_day_end_hour", models.PositiveSmallIntegerField(default=0, verbose_name="fin du service")),
                ("sheet", models.CharField(blank=True, max_length=100, verbose_name="feuille")),
                ("day_column", models.CharField(blank=True, max_length=100, verbose_name="colonne du jour")),
                ("time_column", models.CharField(blank=True, max_length=100, verbose_name="colonne de l'heure")),
                ("product_column", models.CharField(blank=True, max_length=100, verbose_name="colonne du produit")),
                (
                    "quantity_column",
                    models.CharField(blank=True, max_length=100, verbose_name="colonne de la quantité"),
                ),
                ("amount_column", models.CharField(blank=True, max_length=100, verbose_name="colonne du montant TTC")),
                (
                    "amount_ht_column",
                    models.CharField(blank=True, max_length=100, verbose_name="colonne du montant HT"),
                ),
                ("rate_column", models.CharField(blank=True, max_length=100, verbose_name="colonne du taux de TVA")),
                (
                    "category_column",
                    models.CharField(blank=True, max_length=100, verbose_name="colonne de la catégorie"),
                ),
                (
                    "typology_column",
                    models.CharField(blank=True, max_length=100, verbose_name="colonne de la typologie"),
                ),
                (
                    "method_column",
                    models.CharField(blank=True, max_length=100, verbose_name="colonne du moyen de paiement"),
                ),
                ("paid_column", models.CharField(blank=True, max_length=100, verbose_name="colonne du montant payé")),
                (
                    "amount_is_unit_price",
                    models.BooleanField(default=False, verbose_name="le montant est un prix unitaire"),
                ),
                ("method_map", models.TextField(blank=True, verbose_name="moyens de paiement")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="salesimportjob",
            name="source",
            field=models.CharField(default="laddition", max_length=20),
        ),
    ]
