# Generated by Django 5.2.17 on 2026-10-02 12:59

import datetime

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dispatch",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "kind",
                    models.CharField(
                        choices=[("reminder", "rappel"), ("event", "alerte"), ("test", "essai")],
                        max_length=10,
                        verbose_name="type",
                    ),
                ),
                ("reminder_id", models.PositiveIntegerField(blank=True, null=True, verbose_name="rappel")),
                ("event_rule_id", models.PositiveIntegerField(blank=True, null=True, verbose_name="alerte")),
                ("rule_name", models.CharField(max_length=120, verbose_name="règle")),
                ("event", models.CharField(blank=True, max_length=60, verbose_name="événement")),
                ("outcome", models.CharField(blank=True, max_length=30, verbose_name="résultat")),
                ("scheduled_for", models.DateTimeField(blank=True, null=True, verbose_name="prévu pour")),
                ("dedupe_key", models.CharField(max_length=200, unique=True)),
                ("title", models.CharField(max_length=80, verbose_name="titre")),
                ("body", models.CharField(blank=True, max_length=400, verbose_name="message")),
                ("target", models.CharField(blank=True, max_length=500, verbose_name="page à ouvrir")),
                ("ttl", models.PositiveIntegerField(verbose_name="durée de vie (s)")),
                ("topic", models.CharField(blank=True, max_length=32)),
                ("recipient_ids", models.JSONField(blank=True, null=True, verbose_name="destinataires")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "en attente"),
                            ("sending", "en cours"),
                            ("sent", "envoyé"),
                            ("partial", "partiel"),
                            ("failed", "échec"),
                            ("no_device", "aucun appareil"),
                            ("skipped", "sauté"),
                            ("missed", "manqué"),
                            ("disabled", "désactivé"),
                        ],
                        default="pending",
                        max_length=12,
                        verbose_name="état",
                    ),
                ),
                ("detail", models.CharField(blank=True, max_length=300, verbose_name="détail")),
                ("devices", models.PositiveSmallIntegerField(default=0, verbose_name="appareils")),
                ("delivered", models.PositiveSmallIntegerField(default=0, verbose_name="reçus")),
                (
                    "created_at",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name="créé le"),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True, verbose_name="envoyé le")),
            ],
            options={
                "verbose_name": "envoi",
                "verbose_name_plural": "envois",
                "ordering": ["-created_at", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="EventRule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("event", models.CharField(max_length=60, unique=True, verbose_name="événement")),
                ("outcomes", models.JSONField(default=list, verbose_name="résultats")),
                ("target", models.CharField(blank=True, max_length=500, verbose_name="page à ouvrir")),
                ("all_members", models.BooleanField(default=False, verbose_name="tous les membres")),
                ("recipient_ids", models.JSONField(blank=True, default=list, verbose_name="destinataires")),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, verbose_name="créée le")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="modifiée le")),
            ],
            options={
                "verbose_name": "alerte",
                "verbose_name_plural": "alertes",
                "ordering": ["event"],
            },
        ),
        migrations.CreateModel(
            name="NotificationSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("night_ends_at", models.TimeField(default=datetime.time(6, 0), verbose_name="la nuit se termine à")),
                (
                    "last_tick_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="dernier passage du planificateur"),
                ),
            ],
            options={
                "verbose_name": "réglage des notifications",
                "verbose_name_plural": "réglages des notifications",
            },
        ),
        migrations.CreateModel(
            name="Reminder",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=80, verbose_name="nom")),
                ("title", models.CharField(max_length=80, verbose_name="titre")),
                ("body", models.CharField(blank=True, max_length=400, verbose_name="message")),
                ("target", models.CharField(max_length=500, verbose_name="page à ouvrir")),
                ("weekdays", models.CharField(max_length=14, verbose_name="soirs")),
                ("times", models.CharField(max_length=120, verbose_name="heures")),
                ("skip_if", models.CharField(blank=True, max_length=40, verbose_name="ne pas envoyer si")),
                (
                    "skip_hours",
                    models.PositiveSmallIntegerField(
                        default=6,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(48),
                        ],
                        verbose_name="depuis (heures)",
                    ),
                ),
                ("skip_supplier_id", models.PositiveIntegerField(blank=True, null=True, verbose_name="repris par")),
                ("all_members", models.BooleanField(default=True, verbose_name="tous les membres")),
                ("recipient_ids", models.JSONField(blank=True, default=list, verbose_name="destinataires")),
                ("is_active", models.BooleanField(default=True, verbose_name="actif")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, verbose_name="créé le")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="modifié le")),
            ],
            options={
                "verbose_name": "rappel",
                "verbose_name_plural": "rappels",
                "ordering": ["name", "pk"],
            },
        ),
    ]
